apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: aog4atulg-nodejs
  janus-idp.io/tekton: aog4atulg-nodejs
  backstage.io/kubernetes-id: aog4atulg-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: aog4atulg-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
